### ISSUE TITLE
Two recommended ciphers in the "modern" suite are weak according to SSLLabs

### ISSUE THREAD

**Issue by Timvde** [mozilla/server-side-tls#248] opened 2019-05-22 20:04 UTC
I configured nginx with only TLSv1.2 and TLSv1.3 support, with the recommended ciphers from the modern suite. According to the SSL test on https://www.ssllabs.com/ssltest/, `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384` and `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256` are considered "weak".

In the cipher list on the wiki, this matches with `ECDHE-RSA-AES256-SHA384 ` and `ECDHE-RSA-AES128-SHA256`. As confirmation, if I remove those from my nginx config, all remaining ciphers are considered strong.

**Comment by tomato42** [comment] 2019-05-22 20:11
duplicate of #244

**Closed as completed by tomato42** 2019-05-22 20:11 UTC
Labels: duplicate
