### ISSUE TITLE
No DH parameter tunable is needed for modern configuration

### ISSUE THREAD

**Issue by varnav** [mozilla/server-side-tls#164] opened 2016-09-29 14:54 UTC
Select modern config for HAProxy. You will see this line:

`tune.ssl.default-dh-param 2048`

Select modern config for Nginx. You will see this line:

`ssl_dhparam /path/to/dhparam.pem;`

But [modern recommendation](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) says:

> DH Parameter size: None (disabled entirely)

So, we do not need any DH param settings for modern configs.

**Comment by gene1wood** [comment] 2019-04-10 22:27
Duplicate of #148

**Closed as completed by gene1wood** 2019-04-10 22:27 UTC
Labels: duplicate, config generator
