### ISSUE TITLE
Modern configuration generator still points to DH param files

### ISSUE THREAD

**Issue by april** [mozilla/server-side-tls#148] opened 2016-07-07 20:28 UTC
Even though the modern configuration uses only ECDHE, for some generators, it still points to a dhparam file, even thought it isn't needed.  Those lines should probably be omitted.

**Comment by FlorentATo** [comment] 2016-08-18 07:41
I was about to report the same issue.
Not sure it worth opening a ticket but it might be useful to specify the curve used for ECC ciphers i.e. `ssl_ecdh_curve secp384r1;` (nginx).

Edit: The [wiki](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) is correct about this:
`DH Parameter size: None (disabled entirely)`

**Comment by gene1wood** [comment] 2019-04-10 22:32
Duplicate of #123

**Closed as completed by gene1wood** 2019-04-10 22:32 UTC
Labels: bug, config generator
